### ISSUE TITLE
Report for resources 'URL' and 'URLProvider'

### ISSUE THREAD

**Issue by thikade** [IBM/websphere-cct#10]
I can see that the WAS AdminConfig types "URL" and "URLProvider" get collected by ConfigDumper , but there is no report containing these. It might be quite easy to add them to the resources-report as they are similar to the already existing REProvider.
Having had a look at the codebase, extending a report or creating a new one is not really intuitive, but I would like to contribute as I need those resources compared.
Could you  provide a high-level documentation of the steps required to implement such a thing as an implementation guideline for contributors?

**Comment by riddlemo** [comment]
Hi Thomas,
        Thank you for your interest in enhancing CCT.  I currently do not 
have any guidelines or documentation for contributors to CCT.  Since CCT 
is now on GitHub and I do want contributors, you have unfortunately 
identified a failing in my documentation that I had not thought of. 
        ConfigDump.py was changed last year to try and gather all of the 
configuration repository even though reports for many configuration items 
are not implemented yet.  This was to support implementing the reports 
retroactively.  There were a few driving factors behind this including 
making the configuration collection code fairly static and allowing for 
implementing reports after configuration collection. To my knowledge, the 
only configuration item that is not gathered is the Key.  This is due to 
parsing issues which can make CNs in the Key elements look like 
configuration IDs. 
        I will need to formalize the following and publish it but here is 
an overview of adding a new Resource report.  Server reports are more 
complicated as I did not have an easily extensible design on my initial 
inception of this tool.  At some point, I need to go convert Server 
reports to follow the Resource report paradigm but that is a large effort. 
 

Change histories:
Any changes made to .py files need to have the change histories at the top 
of the file.  I have included a snippet below.  The "Ref" field is just a 
sequential number.  You need to check ConfigDump.py, ConfigReport.py and 
ConfigUtils.py to find the highest number and increment by one.  The Who 
field is simply your initials

# Date        Ref  Who  Comments
# 4/9/2018    0003 DWR  Create output directory if it does not exist.

Within the code, use REF#### where #### is the number from the Ref column. 
 There are two ways to use this.

Block comments:
#Begin Ref####
#End Ref####

Single line comments put it at the end of the line.
for item in myList:  #Ref####

Code Changes:
Resource reports use the newer design for report definition.  Server 
reports are a series of different Python functions.  Resource reports are 
defined in a data structure that is a list of Dictionaries within a 
Dictionary.  Each table title in a report corresponds to a Configuration 
ID and rows within that table correspond to attributes associated with 
that configuration ID in the configuration repository XML files. 

Since Resource Environment is close to the report that you want, I will 
use that as an example for the format of the entries.  ResourceEnvEntry is 
element type as seen in the configuration ID that is used on wsadmin 
scripting to manipulate the entry.  These are the same configuration IDs 
you will see left justified in the CCT *.cfg dump files. 

Example configuration ID, element type in bold:
MyResourceReference(cells/MyCell/clusters/MyCluster|resources.xml#
ResourceEnvEntry_1389501553053)

Below is a sample of a Resource report definition.  This will produce 
three tables split only by a title.  Each table corresponds to a 
configuration ID.  "Title" is the title that will show up in the report. 
If the resource has some variation of a name attribute, that will show up 
in parenthesis next to the defined title automatically.  "ReportName" 
refers to an entry in ConfigReportAttributes.properties which will have to 
be added, see below.  "ConfigPath" is a path to the configuration ID based 
on a top level configuration ID.  Generally the first ConfigPath is "[]" 
(an empty list)  which means use the supplied configuration ID.  Some 
attributes of the configuration ID may also be configuration IDs 
themselves and comparing the literal Configuration IDs is useless.  As 
such, a new line defining a new table is used and there is a "path" to 
that configuration ID.  The ConfigPath list is a list of attributes to 
navigate to find the correct config ID.  In the example below, "
['referenceable']" means that the value of attribute referenceable is a 
configuration ID and needs a table to report the attributes of it.  If the 
configuration element at "referenceable" had an attribute that referenced 
another config ID then "['referenceable',some_other_attribute']" would 
report that element in a table.  Note, the format of the syntax below is 
significant from the standpoint of ease of reading and extending.  Use 
tabs for indenting when possible.  Spaces can be used after tabs to make 
sure things match up.  Spaces should only be used on continuation lines 
(lines following a "\").  Do not do code indentation with spaces.  The 
rest of the code uses tabs and I am told using mixed tabs and spaces can 
cause weird issues within Python. 

        'ResourceEnvEntry':[{'Title':'Resource Environment 
Entry','ReportName':'rscEnvEntryRsc','ConfigPath':[]},\
 
{'Title':'Referencable','ReportName':'referencableRsc','ConfigPath':['referenceable']},\
                            {'Title':'Resource Environment 
Provider','ReportName':'rscEnvProviderRsc','ConfigPath':['provider']},\
        ], \

At the end of ConfigReport.py there is a long if/elif statement.  You need 
to add a new entry there similar to the one below.  Note the reportType is 
the configuration element type. 

                elif reportType == 'ResourceEnvEntry': #Ref0018
                        ResourceReport(report) #Ref0018

Finally, you need to update ConfigReportAttributes.properties with the 
attributes of the configuration element you actually want to show in the 
reports.  Not all attributes make sense to report.  There will be one line 
per line in the report definition.  The order does not matte as they are 
property value lookups.  The property name is the ReportName above 
appended with a ":attributes".  I did this as I originally envisioned 
needing more than one property per report but so far I have not needed 
this.  There is no need to put a change history in this file as I have not 
been doing this. 

rscEnvProviderRsc:attributes=description,nativepath,isolatedClassLoader,SearchPropertiesService,referenceables,classpath
rscEnvEntryRsc:attributes=jndiName
referencableRsc:attributes=factoryClassname,classname


Finally, if you have PowerPoint, update the PPT with the new reports, 
export it to a PDF and submit those with your code changes.  If you do not 
have PowerPoint, I will do this later.  The above should be enough 
information to implement the two reports you need.  I believe the GitHub 
project is set up such that you can submit your changes for my review and 
inclusion.  Please let me know if you have any questions. 


Regards,
Dennis 


Dennis Riddlemoser, Accelerated Value Specialist
World Wide IBM Software Accelerated Value Program
Phone: (720) 342-5689
Email: riddlemo@us.ibm.com
Visit IBM Software Accelerated Value Program Online

**Comment by thikade** [comment]
Hi Dennis,

thanks a lot for the quick and detailed reply!
I'm going to look into that stuff - probably in the next few days. 
I'll either get back to you with a PR or more questions ;-)

Kind regards,
Thomas

**Comment by thikade** [comment]
Hi Dennis,

thanks to your explanation it was actually quite easy to add URL and URLProvider resources!
  
But I have run into a few problems, maybe due to some misconfiguration or -understanding on my side ...

1.  I added a custom report (see [1]), and it gets generated. **But all URLs are reported inside a single table row**, mixing all names together of the old and new cell!  I would expect several *URL* Tables, one for each unique name pair, with columns for old and new cell.

1. Additionally, when I use cell scope as shown in [1], I also get all URL resources below, on Cluster scope etc. These get added to the single table row of URL resources. It now has ~ 40 columns and is pretty useless for comparisons. I can work around that by using cluster scope in the report, but that way I am omitting the cell scope resources [2]

1.  I then added the 'URL' & 'URLProvider' resources to function `reportAllResourcesByName()`, so that the built-in *Resources* report also generates my new resources, and that worked quite well. Now I get one table for each unique URL name. I believe this is the way to go.

### Q1: 
Is \# 1  a limitation of the custom reports, or did I do something wrong? Are they to be used only for comparing specific resources, ie. by using a resources string of `URL:Resources:1=.*::MySpecificURL1`

### Q2:
Is the scoping issue described in # 2 actually a bug or a feature?

Kind regards
Thomas

[1] Custom URL Report - scoped to Cell
```
URL:ReportType=URL
URL:Title=URLs
URL:Scope:1=Cell
URL:Resources:1=.*::.*
URL:Filename=URLs
``` 

[2] Custom URL Report - scoped to Clusters
```
URL:ReportType=URL
URL:Title=URLs
URL:Scope:1=Cluster
URL:Resources:1=.*::.*<CLUSTERNAME>.*::.*
URL:Filename=URLs
```

**Comment by riddlemo** [comment]
Hi Thomas,
        On Q1, I would need to see the entries for the URL providers in 
the .cfg file to comment on what is going on. 
        On Q2, Likely that is a bug in my regular expressions. 


Regards,
Dennis 


Dennis Riddlemoser, Accelerated Value Specialist
World Wide IBM Software Accelerated Value Program
Phone: (720) 342-5689
Email: riddlemo@us.ibm.com
Visit IBM Software Accelerated Value Program Online

**Comment by thikade** [comment]
Hi,

this is a (abbreviated) cfg dumps for URL resources I got. The new cell's one is basically the same, just with different file-paths inside `spec` attribute.
```
CellSuffix=OLD
"Configuration Services(cells/MYCELL|resources.xml#URL_1394102513174)"
	jndiName=url/my/configuration
	provider="Default URL Provider(cells/MYCELL|resources.xml#URLProvider_1)"
	description="Konfigurationsverzeichnis"
	name="Configuration Services"
	spec=file:///path/to/config
"CTG Cred-Map(cells/MYCELL/clusters/CLUSTER_A|resources.xml#URL_1394102513271)"
	jndiName=url/ctg/CtgCredMap
	provider="Default URL Provider(cells/MYCELL/clusters/CLUSTER_A|resources.xml#URLProvider_1)"
	description=[]
	name="CTG Cred-Map"
	spec=file:///someFileA.xml
"CTG Cred-Map(cells/MYCELL/clusters/CLUSTER_B|resources.xml#URL_1492164527551)"
	jndiName=url/ctg/CtgCredMap
	provider="Default URL Provider(cells/MYCELL/clusters/CLUSTER_B|resources.xml#URLProvider_1)"
	name="CTG Cred-Map"
	spec=file:///someFileB.xml
(cells/MYCELL|virtualhosts.xml#MimeEntry_653)
"CTG Cred-Map(cells/MYCELL/clusters/CLUSTER_C|resources.xml#URL_1394102513289)"
	jndiName=url/ctg/CtgCredMap
	provider="Default URL Provider(cells/MYCELL/clusters/CLUSTER_C|resources.xml#URLProvider_1)"
	description=[]
	name="CTG Cred-Map"
	spec=file:///someFileC.xml
```
Now, with the custom *cell* report definition:
```
URL:ReportType=URL
URL:Title=URLs
URL:Scope:1=Cell
URL:Resources:1=.*::.*
URL:Filename=URLs
```
I do get a single table showing all 2 resources ("CTG Cred-Map", "Configuration Services") on both cell AND cluster scope.  
So the resulting custom URL report looks like this:  

#### URL

Attribute | Config Matches | Configuration Services(cells/MYCELL) | CTG Cred-Map(cells/MYCELL/clusters/CLUSTER_A)| CTG Cred-Map(cells/MYCELL/clusters/CLUSTER_B) | CTG Cred-Map(cells/MYCELL/clusters/CLUSTER_C)
---- | ---- | ---- | ---- |---- | ----
.. | .. | .. | .. | .. | ..

**Comment by riddlemo** [comment]
Integrated changes.  Will be publishing new release today.  Closing issue.
